services:
  postgres:
    image: postgres:16-alpine
    container_name: app-treino-postgres
    environment:
      POSTGRES_DB: app_treino
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - app_treino_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app_treino"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  app_treino_postgres:

